name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a compatible Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install MongoDB client tools
      run: sudo apt-get update && sudo apt-get install -y mongodb-clients

    - name: Wait for MongoDB to be ready
      run: |
        # Simple wait loop for MongoDB service
        for i in $(seq 1 20); do
          nc -z mongodb 27017 && echo "MongoDB is ready!" && break
          echo "Waiting for MongoDB... ($i/20)"
          sleep 1
        done
        nc -z mongodb 27017 || (echo "MongoDB did not start in time!" && exit 1)

    - name: Seed database
      run: |
        export MONGO_URI="mongodb://mongodb:27017/" # Ensure seed script connects to the service
        python seed_db.py

    - name: Run tests
      run: |
        # Ensure app.py can find MongoDB
        export MONGO_URI="mongodb://mongodb:27017/"
        pytest
